// ─── Theme variants for storefront layouts ─────────────────────────────────

export const themeVariants = {
  padrao: {
    containerRounded: 'rounded-xl sm:rounded-2xl',
    elementRounded: 'rounded-xl',
    cardRounded: 'rounded-xl sm:rounded-2xl',
    shadow: 'shadow-sm',
    hoverEffect: 'hover:shadow-md',
    border: 'border-gray-200',
    bg: '#F9FAFB',
    font: '',
    filterActive: 'border-blue-500 bg-blue-50 text-blue-700',
    filterInactive: 'border-gray-200 text-gray-600',
    searchBg: 'bg-gray-50 focus:bg-white',
    inputHeight: 'h-10',
    filterHeight: 'h-9',
    filterBtnHeight: 'h-10',
    filterBtnPx: 'px-3',
    sortHeight: 'h-8',
    sortPx: 'px-2',
    resultsMargin: 'mb-4',
  },
  vtlx: {
    containerRounded: 'rounded-lg',
    elementRounded: 'rounded-full',
    cardRounded: 'rounded-lg',
    shadow: 'shadow-none',
    hoverEffect: 'hover:border-gray-300',
    border: 'border-gray-100',
    bg: '#F9FAFB',
    font: '',
    filterActive: 'border-gray-900 text-gray-900',
    filterInactive: 'border-gray-200 text-gray-600',
    searchBg: 'bg-white',
    inputHeight: 'h-11',
    filterHeight: 'h-10',
    filterBtnHeight: 'h-11',
    filterBtnPx: 'px-4',
    sortHeight: 'h-9',
    sortPx: 'px-3',
    resultsMargin: 'mb-4',
  },
  premium: {
    containerRounded: 'rounded-lg',
    elementRounded: 'rounded-md',
    cardRounded: 'rounded-lg',
    shadow: 'shadow-sm',
    hoverEffect: 'hover:shadow-lg hover:-translate-y-0.5',
    border: 'border-gray-200',
    bg: '#F5F5F0',
    font: '',
    filterActive: 'border-gray-800 bg-gray-900 text-white',
    filterInactive: 'border-gray-300 text-gray-600',
    searchBg: 'bg-white',
    inputHeight: 'h-11',
    filterHeight: 'h-10',
    filterBtnHeight: 'h-11',
    filterBtnPx: 'px-5',
    sortHeight: 'h-9',
    sortPx: 'px-3',
    resultsMargin: 'mb-5',
  },
  vtclass: {
    containerRounded: 'rounded-none',
    elementRounded: 'rounded-none',
    cardRounded: 'rounded-none',
    shadow: 'shadow-none',
    hoverEffect: 'hover:border-gray-400',
    border: 'border-gray-300',
    bg: '#DDDDDD',
    font: 'uppercase tracking-wide',
    filterActive: 'border-gray-700 text-gray-900',
    filterInactive: 'border-gray-300 text-gray-600',
    searchBg: 'bg-white',
    inputHeight: 'h-10',
    filterHeight: 'h-9',
    filterBtnHeight: 'h-10',
    filterBtnPx: 'px-4',
    sortHeight: 'h-9',
    sortPx: 'px-3',
    resultsMargin: 'mb-3',
  },
} as const

export type ThemeKey = keyof typeof themeVariants
export type ThemeVariant = (typeof themeVariants)[ThemeKey]
